Updated Dockerfile

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -13,21 +13,17 @@ RUN apk add --no-cache libc6-compat
 WORKDIR /app
 
 # Install dependencies based on the preferred package manager
-# COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .yarnrc.yml ./
-COPY package.json yarn.lock* .yarnrc.yml ./
-COPY .yarnrc.yml.build ./.yarnrc.yml
-# COPY .yarn ./.yarn
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .yarnrc.yml ./
+COPY .yarn ./.yarn
 
-RUN yarn 
+# if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
 
-
-#RUN \
-#  if [ -f yarn.lock ]; then yarn --network-timeout 100000;  \
-#  elif [ -f package-lock.json ]; then npm ci; \
-#  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
-#  else echo "Lockfile not found." && exit 1; \
-#  fi
-
+RUN \
+  if [ -f yarn.lock ]; then yarn --network-timeout 100000;  \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 RUN echo $(yarn --version)
 RUN ls -lah 
 
@@ -42,14 +38,14 @@ WORKDIR /app
 COPY --from=deps /app/node_modules ./node_modules
 COPY . .
 COPY .env.build .env
-# COPY .yarn ./.yarn
 
 # Next.js collects completely anonymous telemetry data about general usage.
 # Learn more here: https://nextjs.org/telemetry
 # Uncomment the following line in case you want to disable telemetry during the build.
 ENV NEXT_TELEMETRY_DISABLED 1
 
-RUN yarn run build
+# RUN yarn --network-timeout 100000 
+RUN yarn build
 
 # If using npm comment out above and use below instead
 # RUN npm run build
